### PR TITLE
No need to keep class names

### PR DESCRIPTION
**Pull request by vvb2060**
* [ ] Has `CHANGELOG.md` been updated?
* [x] Are tests passing locally?
* [x] Are the files formatted correctly?
* [ ] Did you add unit tests?
* [x] Did you test your change with either the sample apps that are included in the repository or with a blank app that uses your change?
* [x] Did you check UI tests on the sample app? They are not executed on CI.

## Description

`keepclasseswithmembers` keep class names, which is not need because we include class in arguments.

### CODE REVIEW

**Review by MatkovIvan — CHANGES_REQUESTED** [review]
Class names are required for wrapper SDKs (like Xamarin, React-Native, etc)

**Comment by vvb2060** [comment]
Do these libraries (not even Java libraries) require reflection to use appcenter-crashes/appcenter-analytics?  Why not add keep rules to their library?  Most users will not use these libraries.

**Comment by MatkovIvan** [comment]
Unity one [use it for sure](https://github.com/microsoft/appcenter-sdk-unity/blob/a501cf9ce84c93cbad6a3e63c11852d83cfa8762/Assets/AppCenter/Plugins/AppCenterSDK/Analytics/Android/AnalyticsInternal.cs#L14).

Could you please elaborate why exactly is it important for you?
For now this PR cannot be merged as-is because it requires changes in/testing of other parts of the product. But the benefit is not clear.

**Comment by vvb2060** [comment]
I would like to completely obfuscate appcenter, reducing the size of the app is one reason. Another reason is that some users are very wary of telemetry, and they will suspect our app will compromise privacy because of the dex scanner warning without reading our privacy policy. I hope to mitigate this problem.

**Comment by MatkovIvan** [comment]
> reducing the size of the app is one reason

Names of 2 classes won't help with this.

Regarding hiding "annoying" names - ok, it seems valid improvement. But as I mentioned before it requires some additional work from our team, so it cannot be merged now.
Anyway, thanks for your contribution and highlighting this topic!

**Comment by DmitriyKirakosyan** [comment]
I'm closing this PR as stale.

**Pull request closed without merging**
