### PR TITLE
Merge identity to storage + Copyright

### PR DESCRIPTION
**Pull request by guperrot**
Please have a look at our [guidelines for contributions](https://github.com/Microsoft/AppCenter-SDK-Android/blob/develop/CONTRIBUTING.md) and consider the following before you submit the PR:

* [ ] Has `CHANGELOG.md` been updated?
* [ ] Are tests passing locally?
* [x] Are the files formatted correctly?
* [ ] Did you add unit tests?
* [ ] Did you test your change with either the sample apps that are included in the repository or with a blank app that uses your change?
* [ ] Did you check UI tests on the sample app? They are not executed on CI.

## Description

* Merge feature/identity
* Apply copyright to new files on feature/storage

## Related PRs or issues

#989

### CODE REVIEW

**Comment by hovsepm** [comment]
e

**Comment by hovsepm** [comment]
Is there a way to rebase this PR? I'm unable to open it in CodeFlow which allows max 64 commits. It is really hard to review on github.

**Comment by guperrot** [comment]
We don't rebase merge between main branches such as develop/master as storage will be merged back to develop.

**Comment by guperrot** [comment]
This is the only change relevant to storage: https://github.com/Microsoft/AppCenter-SDK-Android/pull/1003/commits/a7849d1bfb7cd4bee83031db2e46d2f26df0edaf

**Pull request merged**
